name: Build BOT
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1        
    - name: Build the Docker image
      run: |
        docker build -t $Repo:$branch -t ${{ github.repository }}:en_US .       
 
    - name: Login to registry
      env:
        DOCKER_USERNAME: si0972
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: echo ${{ secrets.GH_PACK_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
    - name: Pushes the Docker image
      if: github.event_name != 'pull_request' && contains(github.ref, 'actions') != 'true'
      run: docker push si0972/sprokfork
