name: Build BOT
on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1        
    - name: Build the Docker image
      run: docker build -t roxedus/loveherk:en_US .       
 
    - name: Login to registry
      run: echo ${{ secrets.GH_PACK_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      
    - name: Pushes the Docker image
      if: github.event_name != 'pull_request' && contains(github.ref, 'actions') != 'true'
      run: docker push docker.pkg.github.com/roxedus/loveherk/:en_US
